### ISSUE TITLE
SettingsBackup

### ISSUE THREAD

**Issue by lucasvr** [gobolinux/GoboALFS#3]
Some packages are leaving behind Resources/SettingsBackup that make no sense. Bluez is one such example:
``...``
`` /usr/sbin/mkdir -p '/System/Settings/dbus-1/system.d'``
`` /usr/bin/install -c -m 644 src/bluetooth.conf '/System/Settings/dbus-1/system.d'``
``...``
``UpdateSettings: Current and default settings are different``
`` 1      del: Settings/dbus-1/system.d/bluetooth.conf``
``UpdateSettings: Quick-updating settings in /Programs/Bluez``
``UpdateSettings: Backing up settings in /Programs/Bluez/5.41/Resources/SettingsBackup``

We'll have to go through /Programs/*/Current/Resources before shipping the ISO. @hishamhm, care to take a look at Compile/Scripts to figure if this is the expected behavior?

**Comment by hishamhm** [comment]
I wonder if this is because the Resources dir of the recipe includes default settings and the compilation installs other settings of its own.

**Comment by lucasvr** [comment]
It could be. Anyhow, I've noticed that the issue is already addressed by GoboALFS: we remove SettingsBackup when creating binary packages of the programs compiled.
