### ISSUE TITLE
ArchLinux: fails with REV variable

### ISSUE THREAD

**Issue by XuTpuK** [gobolinux/GoboALFS#7]
Having all dependencies, I run:

`./GoboALFS /mydir`

After "lfs config parameters looks good" confirmation, "make" utility fails:

> *** The REV variable is , but can only be 'sysv' or 'systemd'. Stop.

I checked makefile, it really checks REV, but doesn't work:

    ifeq ($(REV),)
        REV = sysv
    endif

**Comment by lucasvr** [comment]
I have introduced several fixes to the tool, including the one that led to the REV variable issue. Please give it another try now.

**Comment by XuTpuK** [comment]
Yep, tried! Now error come much later :)  "sudo not found" here screen: http://imgur.com/a/fsmlq

**Comment by lucasvr** [comment]
The sudo problem is supposed to be gone. Could you try with a fresh tree again?
