### ISSUE TITLE
Installer: missing package descriptions

### ISSUE THREAD

**Issue by lucasvr** [gobolinux/GoboALFS#8]
As reported on gobolinux-users by Vincent, some packages have missing descriptions. We should make sure that GoboALFS populates all packages' Resources/Description file.

**Comment by hishamhm** [comment]
Is the descriptions list from the installer built from the programs' Resources/Description files?

**Comment by lucasvr** [comment]
No, it was not automated at all, it seems. I'm working on this item now and should have a fix soon.
